import { useState } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { useStore } from './store';
import { today } from './data';
import { iso, isAvailable, isOccupied } from './availability.mjs';
type Props={roomId?:string;start:string;end:string;onChange:(start:string,end:string)=>void;mode?:'range'|'single';occupiedDates?:string[];excludeId?:string};
export default function Calendar({roomId,start,end,onChange,mode='range',occupiedDates=[],excludeId}:Props){const {bookings}=useStore();const [month,setMonth]=useState(()=>new Date((start||today).slice(0,7)+'-01T12:00:00'));const [hint,setHint]=useState('');const active=bookings.filter(b=>b.id!==excludeId);const count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();const offset=(month.getDay()+6)%7;const choose=(day:string)=>{setHint('');if(mode==='single'){onChange(day,'');return}if(!start||end||day<=start){onChange(day,'');return}if(roomId&&!isAvailable(roomId,start,day,active)){setHint('Izabrani period sadrži zauzete noći. Izaberite drugi dolazak.');onChange(day,'');return}onChange(start,day)};
 return <div className="availability-calendar"><div className="calendar-heading"><button type="button" aria-label="Prethodni mesec" disabled={month<=new Date(today.slice(0,7)+'-01T12:00:00')} onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft size={18}/></button><strong>{month.toLocaleDateString('sr-Latn-RS',{month:'long',year:'numeric'})}</strong><button type="button" aria-label="Sledeći mesec" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight size={18}/></button></div><div className="calendar-grid">{['P','U','S','Č','P','S','N'].map((d,i)=><span className="weekday" key={'w'+i}>{d}</span>)}{Array.from({length:offset},(_,i)=><span key={'e'+i}/>)}{Array.from({length:count},(_,i)=>{const day=iso(new Date(month.getFullYear(),month.getMonth(),i+1));const busy=roomId?isOccupied(roomId,day,active):occupiedDates.includes(day);const checkout=mode==='range'&&!!start&&!end&&day>start&&!!roomId&&isAvailable(roomId,start,day,active);const disabled=day<today||(busy&&!checkout);const selected=day===start||day===end;return <button type="button" key={day} aria-label={`${day}${busy?' — zauzeto':''}`} aria-pressed={selected} title={busy?'Zauzeto':day===today?'Danas':'Dostupno'} disabled={disabled} className={`${busy?'occupied ':''}${selected?'selected ':''}${start&&end&&day>start&&day<end?'in-range ':''}${day===today?'today':''}`} onClick={()=>choose(day)}>{i+1}</button>})}</div><div className="calendar-legend"><span><i/>Dostupno</span><span><i className="busy"/>Zauzeto</span><span><i className="chosen"/>Vaš izbor</span></div><p className="calendar-hint" aria-live="polite">{hint||(mode==='single'?'Izaberite slobodan datum za svoju proslavu.':!start?'Izaberite datum dolaska.':!end?'Sada izaberite datum odlaska.':'Vaš termin je izabran.')}</p></div>
}
