import {useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {ArrowLeft,ArrowUpRight,Check,Users,Maximize,Wifi,Clock} from 'lucide-react';
import {rooms,today} from './data';
import {useStore} from './store';
import {isAvailable,addDays} from './availability.mjs';
import Calendar from './Calendar';
import './booking.css';
export default function Room(){const {id}=useParams();const room=rooms.find(r=>r.id===id);const {bookings}=useStore();const [start,setStart]=useState('');const [end,setEnd]=useState('');const [expanded,setExpanded]=useState(false);if(!room)return <main className="room-page"><Link to="/">← Nazad na početnu</Link><h1>Soba nije pronađena.</h1></main>;const available=isAvailable(room.id,start,end,bookings)&&start>=today;return <main className="room-page"><div className="stay-top"><Link to="/#sobe"><ArrowLeft size={18}/> Naše sobe</Link><Link to="/" className="stay-brand">CRYSTAL <span>LIGHT</span></Link></div><section className="room-intro"><div className="eyebrow">VAŠ PROSTOR ZA ODMOR · SOBA {room.number}</div><h1>{room.name}<span>{room.subtitle}</span></h1><p>{room.description}</p></section><button className={'room-detail-photo '+(expanded?'expanded':'')} onClick={()=>setExpanded(!expanded)} aria-label={expanded?'Smanji fotografiju':'Uvećaj fotografiju'}><img src={room.image} alt={room.name+' — enterijer sobe'}/><span><Maximize size={16}/> {expanded?'Smanji':'Pogledajte prostor'}</span></button><div className="room-body"><section><div className="room-specs"><span><Users/> Do {room.capacity} gosta</span><span><Maximize/> {room.size} m²</span><span><Wifi/> Besplatan Wi-Fi</span></div><div className="eyebrow">PROMIŠLJENO DO DETALJA</div><h2>Sve što vam je potrebno.<br/><i>I malo više.</i></h2><div className="room-amenities">{room.amenities.map(a=><span key={a}><Check size={16}/>{a}</span>)}</div><div className="stay-note"><Clock size={20}/><div><strong>Vreme je na vašoj strani.</strong><p>Prijava od 14:00 · Odjava do 11:00.<br/>Za poseban dogovor pišite nam uz rezervaciju.</p></div></div></section><aside id="dostupnost" className="stay-card room-reserve"><div className="price-line"><span><b>€{room.price}</b> / noć</span><small>Demo cena</small></div><h3>Izaberite svoje datume</h3><Calendar roomId={room.id} start={start} end={end} onChange={(s,e)=>{setStart(s);setEnd(e)}}/><p className="stay-fine">Kalendar prikazuje raspoloživost ove sobe. Odlazak je moguć na dan nove prijave.</p>{start&&end&&!available&&<p className="stay-error" role="alert">Ovaj termin nije slobodan. Izaberite druge datume.</p>}<Link className={'stay-primary '+(start&&end&&!available?'disabled':'')} aria-disabled={!!(start&&end&&!available)} onClick={e=>{if(start&&end&&!available)e.preventDefault()}} to={'/booking?room='+room.id+'&start='+(start||addDays(today,2))+'&end='+(end||addDays(today,3))+'&guests=2'}>Rezervišite boravak <ArrowUpRight size={18}/></Link><div className="stay-fine center">Direktna rezervacija. Ličan pristup.</div></aside></div><Link className="stay-text-link" to="/#sobe">Istražite ostale sobe <ArrowUpRight size={17}/></Link></main>}
